language: objective-c
compiler:
- gcc
env:
  matrix:
  - NODE_NVM_VERSION="0.10"
  - NODE_NVM_VERSION="0.8"
before_install:
- export platform=$(uname -s | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/")
- if [[ "$platform" == "linux" ]]; then sudo apt-get install -y nasm; fi
- if [[ "$platform" == "darwin" ]]; then sudo brew install gpg; fi
- git clone https://github.com/creationix/nvm.git ../.nvm
- source ../.nvm/nvm.sh
- nvm install $NODE_NVM_VERSION
- nvm use $NODE_NVM_VERSION
- node --version
- npm --version
- ./test/travis-deps.sh
install:
- npm install
script:
- npm test
after_success:
- ./test/travis-publish.sh
